spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: test
      password: test
      authentication-database: admin
  servlet:
    multipart:
      max-request-size: 3000MB
      max-file-size: 300MB

#spring.data.mongodb.address=localhost:27017
#spring.data.mongodb.database=testdb
#spring.data.mongodb.username=test
#spring.data.mongodb.password=test
#
#  # Configure spring.data.mongodbDB Pool
#spring.data.mongodb.min-connections-per-host=10
#spring.data.mongodb.max-connections-per-host=100
#spring.data.mongodb.threads-allowed-to-block-for-connection-multiplier=5
#spring.data.mongodb.server-selection-timeout=30000
#spring.data.mongodb.max-wait-time=120000
#spring.data.mongodb.max-connection-idel-time=0
#spring.data.mongodb.max-connection-life-time=0
#spring.data.mongodb.connect-timeout=10000
#spring.data.mongodb.socket-timeout=0
#spring.data.mongodb.socket-keep-alive=false
#spring.data.mongodb.ssl-enabled=true
#spring.data.mongodb.ssl-invalid-host-name-allowed=true
#spring.data.mongodb.always-use-m-beans=false
#spring.data.mongodb.heartbeat-socket-timeout=20000
#spring.data.mongodb.heartbeat-connect-timeout=20000
#spring.data.mongodb.min-heartbeat-frequency=500
#spring.data.mongodb.heartbeat-frequency=10000
#spring.data.mongodb.local-threshold=15
#spring.data.mongodb.authentication-database=admin

#spring:
#  datasource:
#    username: postgres
#    driver-class-name: org.postgresql.Driver
#    password: root
#    url: jdbc:postgresql://localhost:5432/test_data?currentSchema=test1
#  jpa:
#    show-sql: true
#    generate-ddl: false
#    hibernate:
server:
  port: 7890

#      ddl-auto: update