server:
  port: 9001
management:
  endpoint:
    health:
      # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: testClient
  boot:
    admin:
      client:
        url: http://localhost:9002