spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: h2db
    password: root
    url: jdbc:h2:file:D:\testdata\jpa-db
  h2:
    # 配置 h2 控制台界面
    console:
      # 默认为false关闭控制台
      enabled: true
      path: /h2console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by:
          #数据库在排序的时候，DESC下NULL默认在最前，此处设置为最后
          default_null_ordering: last
#          default_null_ordering: first
server:
  port: 9003
