spring:
  datasource:
    url: jdbc:h2:file:D:\testdata\testh2db
    username: h2db
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9909