xxl:
  job:
    admin:
#      任务调度中心地址
      addresses: http://127.0.0.1:8080/xxl-job-admin
#      当前项目的配置
    executor:
      appname: xxl-job-demo
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 1
      ip:
      port: 9999
      address:
    accessToken:
server:
  port: 9090